---
DEBUG: true
dbConfig:
  DB_NAME: yeu-ai
modelConfig:
  MODELS_DIR: model_files
  INTENT_MODEL_NAME: intent.model
  TRAIN_DATA_NAME: intent.txt
  DEFAULT_FALLBACK_INTENT_NAME: fallback
  DEFAULT_WELCOME_INTENT_NAME: init_conversation

DB_IMPORT: true
DB_EXPORT: true
