---
DEBUG: true
dbConfig:
  DB_NAME: yeu-ai
modelConfig:
  MODELS_DIR: model_files
  INTENT_MODEL_NAME: intent.model
  TRAIN_DATA_NAME: intent.txt
  DEFAULT_FALLBACK_INTENT_NAME: fallback
  DEFAULT_WELCOME_INTENT_NAME: init_conversation
crfConfig:
  c1: 1.0
  c2: 0.001
  max_iterations: 300
  feature_possible_transitions: 1

DB_IMPORT: true
DB_EXPORT: true
